{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "8358dbb4",
   "metadata": {},
   "source": [
    "# 📊 Análise de Chat do WhatsApp\n",
    "\n",
    "Este notebook analisa conversas exportadas do WhatsApp e gera estatísticas sobre:\n",
    "- Período e volume de mensagens\n",
    "- Usuários mais ativos\n",
    "- Uso de palavrões\n",
    "- Uso de Emojis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "70e6019b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Início da conversa: 25/12/2025 09:47:53\n",
      "Fim da conversa: 04/05/2026 10:38:42\n",
      "Período total: 130 dias e 0 horas.\n",
      "Total de mensagens: 12712\n",
      "Média de mensagens por dia: 97.76\n"
     ]
    }
   ],
   "source": [
    "# EXPORTE A CONVERSA EM UM ARQUIVO TXR E DEIXE NA RIZ DA PASTA COM O NOME _chat.txt\n",
    "\n",
    "import re\n",
    "from datetime import datetime\n",
    "\n",
    "file_path = '_chat.txt'\n",
    "\n",
    "# Regex para encontrar a data no formato do WhatsApp: [dd/mm/yyyy, HH:MM:SS]\n",
    "date_pattern = re.compile(r'\\[(\\d{2}/\\d{2}/\\d{4}), (\\d{2}:\\d{2}:\\d{2})\\]')\n",
    "\n",
    "first_date = None\n",
    "last_date = None\n",
    "total_messages = 0\n",
    "\n",
    "try:\n",
    "    with open(file_path, 'r', encoding='utf-8') as f:\n",
    "        for line in f:\n",
    "            match = date_pattern.search(line)\n",
    "            if match:\n",
    "                total_messages += 1\n",
    "\n",
    "                date_str = f\"{match.group(1)} {match.group(2)}\"\n",
    "                try:\n",
    "                    dt = datetime.strptime(date_str, '%d/%m/%Y %H:%M:%S')\n",
    "                    if first_date is None:\n",
    "                        first_date = dt\n",
    "                    last_date = dt\n",
    "                except ValueError:\n",
    "                    continue\n",
    "\n",
    "    if first_date and last_date:\n",
    "        print(f\"Início da conversa: {first_date.strftime('%d/%m/%Y %H:%M:%S')}\")\n",
    "        print(f\"Fim da conversa: {last_date.strftime('%d/%m/%Y %H:%M:%S')}\")\n",
    "        \n",
    "        delta = last_date - first_date\n",
    "\n",
    "        print(f\"Período total: {delta.days} dias e {delta.seconds // 3600} horas.\")\n",
    "        print(f\"Total de mensagens: {total_messages}\")\n",
    "\n",
    "        # 🔥 Média por dia (precisa, considerando horas)\n",
    "        total_days = max(delta.total_seconds() / 86400, 1)\n",
    "        media = total_messages / total_days\n",
    "\n",
    "        print(f\"Média de mensagens por dia: {media:.2f}\")\n",
    "\n",
    "    else:\n",
    "        print(\"Não foi possível encontrar datas válidas no arquivo.\")\n",
    "\n",
    "except FileNotFoundError:\n",
    "    print(f\"Arquivo '{file_path}' não encontrado.\")\n",
    "except Exception as e:\n",
    "    print(f\"Ocorreu um erro: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "top_20_users_direct_txt",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Top 20 usuários por quantidade de mensagens:\n",
      "--------------------------------------------------\n",
      "1. ~ Silvana 🌴🪻: 1745 mensagens\n",
      "2. ~ Thiago Nascimento: 948 mensagens\n",
      "3. ~ Paulo Falcão: 802 mensagens\n",
      "4. ~ Greicy Macedo: 585 mensagens\n",
      "5. ~ Thelma lunna 🕸️🕸️🌺🌺🌺🔥🔥🔥🕷️🕷️🕷️: 557 mensagens\n",
      "6. ~ Rômulo 🫡❣️: 541 mensagens\n",
      "7. ~ Emily: 468 mensagens\n",
      "8. ~ Gilliard N Aguiar: 375 mensagens\n",
      "9. ~ Naina Holanda: 370 mensagens\n",
      "10. ~ Carlos Emanuel Cearense: 361 mensagens\n",
      "11. ~ Sara: 358 mensagens\n",
      "12. ~ Ana Sabino: 352 mensagens\n",
      "13. ~ Nattanfotos: 339 mensagens\n",
      "14. ~ NF: 323 mensagens\n",
      "15. ~ Leonardo Trajano: 304 mensagens\n",
      "16. ~ Letícia Sousa: 300 mensagens\n",
      "17. ~ Álvaro 🐍: 276 mensagens\n",
      "18. ~ Emerson Silva: 261 mensagens\n",
      "19. ~ Roberta 🪷: 260 mensagens\n",
      "20. André: 223 mensagens\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "from collections import Counter\n",
    "\n",
    "file_path = '_chat.txt'\n",
    "# Regex para extrair o usuário que enviou a mensagem\n",
    "pattern = re.compile(r'\\[\\d{2}/\\d{2}/\\d{4}, \\d{2}:\\d{2}:\\d{2}\\] (.*?):')\n",
    "\n",
    "user_counts = Counter()\n",
    "\n",
    "try:\n",
    "    with open(file_path, 'r', encoding='utf-8') as f:\n",
    "        for line in f:\n",
    "            if not line.strip():\n",
    "                continue\n",
    "                \n",
    "            match = pattern.search(line)\n",
    "            if match:\n",
    "                user = match.group(1)\n",
    "                user_counts[user] += 1\n",
    "\n",
    "    print(\"Top 20 usuários por quantidade de mensagens:\")\n",
    "    print(\"-\" * 50)\n",
    "    \n",
    "    for rank, (user, count) in enumerate(user_counts.most_common(20), 1):\n",
    "        print(f\"{rank}. {user}: {count} mensagens\")\n",
    "        \n",
    "except FileNotFoundError:\n",
    "    print(f\"Erro: Arquivo '{file_path}' não encontrado.\")\n",
    "except Exception as e:\n",
    "    print(f\"Ocorreu um erro ao processar o arquivo: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "profanity_analysis",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Análise de uso das palavras: porra, viado, baitola, raparida, fdp, filho da puta, puta, caralho, cacete, merda, bosta, inferno, arrombado, orrombada, otário, otária, idiota, imbecil, retardado, vsf, vai se fuder, se fudeu, vtnc, tomar no cu, foda-se, krl, krai, kct, tnc, cacete, desgraçado, desgraçada, vagabundo, vagabunda, foda, pqp\n",
      "------------------------------------------------------------\n",
      "1. ~ Leonardo Trajano: 10 ocorrências\n",
      "2. ~ Naina Holanda: 7 ocorrências\n",
      "3. ~ Álvaro 🐍: 5 ocorrências\n",
      "4. ~ ℓires: 4 ocorrências\n",
      "5. ~ Erik Dias: 4 ocorrências\n",
      "6. ~ Thelma lunna 🕸️🕸️🌺🌺🌺🔥🔥🔥🕷️🕷️🕷️: 4 ocorrências\n",
      "7. André: 2 ocorrências\n",
      "8. ~ Nattanfotos: 2 ocorrências\n",
      "9. ~ Paulo Falcão: 2 ocorrências\n",
      "10. ~ Silvana 🌴🪻: 2 ocorrências\n",
      "11. ~ Sara: 2 ocorrências\n",
      "12. ~ NF: 2 ocorrências\n",
      "13. ~ Ana Sabino: 2 ocorrências\n",
      "14. ~ Emerson Silva: 2 ocorrências\n",
      "15. ~ Axel Ribeiro 🇧🇷🇬🇧: 2 ocorrências\n",
      "16. ~ João Henrique: 2 ocorrências\n",
      "17. ~ Emily: 1 ocorrências\n",
      "18. ~ .: 1 ocorrências\n",
      "19. ~ Roberta 🪷: 1 ocorrências\n",
      "20. ~ Paulo Henrique: 1 ocorrências\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "from collections import Counter\n",
    "\n",
    "file_path = '_chat.txt'\n",
    "# Lista de palavras para análise\n",
    "target_words = ['porra', 'viado', 'baitola', 'raparida', 'fdp', 'filho da puta', 'puta','caralho','cacete','merda','bosta','inferno','arrombado','orrombada','otário','otária','idiota','imbecil','retardado','vsf','vai se fuder','se fudeu','vtnc','tomar no cu','foda-se','krl','krai','kct','tnc', 'cacete', 'desgraçado', 'desgraçada','vagabundo', 'vagabunda','foda','pqp' ]\n",
    "# Regex para detectar o início de uma mensagem e o usuário\n",
    "msg_pattern = re.compile(r'\\[\\d{2}/\\d{2}/\\d{4}, \\d{2}:\\d{2}:\\d{2}\\] (.*?): (.*)')\n",
    "\n",
    "user_offensive_counts = Counter()\n",
    "\n",
    "try:\n",
    "    with open(file_path, 'r', encoding='utf-8') as f:\n",
    "        current_user = None\n",
    "        for line in f:\n",
    "            match = msg_pattern.search(line)\n",
    "            if match:\n",
    "                current_user = match.group(1)\n",
    "                content = match.group(2).lower()\n",
    "            else:\n",
    "                # Linha de continuação de mensagem anterior\n",
    "                content = line.lower()\n",
    "            \n",
    "            if current_user:\n",
    "                for word in target_words:\n",
    "                    # Busca a palavra como termo isolado (ignorando case)\n",
    "                    # Usamos regex para garantir que não pegue a palavra dentro de outra (ex: 'importante' não conta como 'porra')\n",
    "                    matches = re.findall(rf'\\b{word}\\b', content)\n",
    "                    user_offensive_counts[current_user] += len(matches)\n",
    "\n",
    "    print(f\"Análise de uso das palavras: {', '.join(target_words)}\")\n",
    "    print(\"-\" * 60)\n",
    "    \n",
    "    # Ordenar e mostrar os top 20 profanos\n",
    "    sorted_users = user_offensive_counts.most_common(20)\n",
    "    \n",
    "    if not sorted_users or sum(user_offensive_counts.values()) == 0:\n",
    "        print(\"Nenhuma dessas palavras foi encontrada na conversa.\")\n",
    "    else:\n",
    "        for rank, (user, total) in enumerate(sorted_users, 1):\n",
    "            if total > 0:\n",
    "                print(f\"{rank}. {user}: {total} ocorrências\")\n",
    "\n",
    "except FileNotFoundError:\n",
    "    print(f\"Erro: Arquivo '{file_path}' não encontrado.\")\n",
    "except Exception as e:\n",
    "    print(f\"Erro ao processar: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "weekday_analysis",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mensagens por dia da semana:\n",
      "------------------------------\n",
      "Segunda-feira: 810 mensagens\n",
      "Terça-feira: 2116 mensagens\n",
      "Quarta-feira: 2852 mensagens\n",
      "Quinta-feira: 2229 mensagens\n",
      "Sexta-feira: 1856 mensagens\n",
      "Sábado: 1630 mensagens\n",
      "Domingo: 1219 mensagens\n",
      "\n",
      "O dia com mais mensagens é Quarta-feira com 2852 mensagens.\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "from datetime import datetime\n",
    "from collections import Counter\n",
    "\n",
    "file_path = '_chat.txt'\n",
    "# Regex para encontrar a data no formato [dd/mm/yyyy, HH:MM:SS]\n",
    "date_pattern = re.compile(r'\\[(\\d{2}/\\d{2}/\\d{4}), \\d{2}:\\d{2}:\\d{2}\\]')\n",
    "\n",
    "days_count = Counter()\n",
    "days_map = {\n",
    "    'Monday': 'Segunda-feira',\n",
    "    'Tuesday': 'Terça-feira',\n",
    "    'Wednesday': 'Quarta-feira',\n",
    "    'Thursday': 'Quinta-feira',\n",
    "    'Friday': 'Sexta-feira',\n",
    "    'Saturday': 'Sábado',\n",
    "    'Sunday': 'Domingo'\n",
    "}\n",
    "\n",
    "try:\n",
    "    with open(file_path, 'r', encoding='utf-8') as f:\n",
    "        for line in f:\n",
    "            match = date_pattern.search(line)\n",
    "            if match:\n",
    "                date_str = match.group(1)\n",
    "                dt = datetime.strptime(date_str, '%d/%m/%Y')\n",
    "                day_name = dt.strftime('%A')\n",
    "                days_count[days_map[day_name]] += 1\n",
    "\n",
    "    print(\"Mensagens por dia da semana:\")\n",
    "    print(\"-\" * 30)\n",
    "    ordered_days = ['Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', 'Domingo']\n",
    "    for day in ordered_days:\n",
    "        print(f\"{day}: {days_count[day]} mensagens\")\n",
    "\n",
    "    if days_count:\n",
    "        most_active_day = days_count.most_common(1)[0]\n",
    "        print(f\"\\nO dia com mais mensagens é {most_active_day[0]} com {most_active_day[1]} mensagens.\")\n",
    "\n",
    "except FileNotFoundError:\n",
    "    print(f\"Arquivo '{file_path}' não encontrado.\")\n",
    "except Exception as e:\n",
    "    print(f\"Erro: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "hourly_analysis",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Distribuição de mensagens por horário:\n",
      "----------------------------------------\n",
      "00:00 - 01:00 (317 mensagens)\n",
      "01:00 - 02:00 (375 mensagens)\n",
      "02:00 - 03:00 (24 mensagens)\n",
      "03:00 - 04:00 (22 mensagens)\n",
      "04:00 - 05:00 (20 mensagens)\n",
      "05:00 - 06:00 (20 mensagens)\n",
      "06:00 - 07:00 (137 mensagens)\n",
      "07:00 - 08:00 (201 mensagens)\n",
      "08:00 - 09:00 (382 mensagens)\n",
      "09:00 - 10:00 (632 mensagens)\n",
      "10:00 - 11:00 (737 mensagens)\n",
      "11:00 - 12:00 (836 mensagens)\n",
      "12:00 - 13:00 (653 mensagens)\n",
      "13:00 - 14:00 (893 mensagens)\n",
      "14:00 - 15:00 (833 mensagens)\n",
      "15:00 - 16:00 (497 mensagens)\n",
      "16:00 - 17:00 (567 mensagens)\n",
      "17:00 - 18:00 (453 mensagens)\n",
      "18:00 - 19:00 (567 mensagens)\n",
      "19:00 - 20:00 (870 mensagens)\n",
      "20:00 - 21:00 (1139 mensagens)\n",
      "21:00 - 22:00 (1070 mensagens)\n",
      "22:00 - 23:00 (936 mensagens)\n",
      "23:00 - 00:00 (531 mensagens)\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "from collections import Counter\n",
    "\n",
    "file_path = '_chat.txt'\n",
    "# Regex para extrair a hora: [dd/mm/yyyy, HH:MM:SS]\n",
    "time_pattern = re.compile(r'\\[\\d{2}/\\d{2}/\\d{4}, (\\d{2}):\\d{2}:\\d{2}\\]')\n",
    "\n",
    "hour_counts = Counter()\n",
    "\n",
    "try:\n",
    "    with open(file_path, 'r', encoding='utf-8') as f:\n",
    "        for line in f:\n",
    "            match = time_pattern.search(line)\n",
    "            if match:\n",
    "                hour = int(match.group(1))\n",
    "                hour_counts[hour] += 1\n",
    "\n",
    "    print(\"Distribuição de mensagens por horário:\")\n",
    "    print(\"-\" * 40)\n",
    "    for h in range(24):\n",
    "        next_h = (h + 1) % 24\n",
    "        count = hour_counts.get(h, 0)\n",
    "        print(f\"{h:02d}:00 - {next_h:02d}:00 ({count} mensagens)\")\n",
    "\n",
    "except FileNotFoundError:\n",
    "    print(f\"Arquivo '{file_path}' não encontrado.\")\n",
    "except Exception as e:\n",
    "    print(f\"Erro: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "e72a979f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total de emojis utilizados: 2297\n",
      "----------------------------------------\n",
      "Os 20 emojis mais frequentes:\n",
      "🏼: 143\n",
      "👏: 143\n",
      "😂: 124\n",
      "😅: 107\n",
      "🤣: 94\n",
      "🏻: 89\n",
      "🙌: 87\n",
      "🤘: 74\n",
      "🏽: 59\n",
      "🥲: 55\n",
      "😆: 52\n",
      "🙏: 45\n",
      "😬: 43\n",
      "🫠: 42\n",
      "🤭: 40\n",
      "🔥: 39\n",
      "😌: 38\n",
      "😄: 34\n",
      "😊: 33\n",
      "👍: 30\n",
      "\n",
      "Top 10 usuários que mais usam emojis:\n",
      "~ Silvana 🌴🪻: 308 emojis\n",
      "~ Thiago Nascimento: 302 emojis\n",
      "~ Greicy Macedo: 243 emojis\n",
      "~ Paulo Falcão: 140 emojis\n",
      "~ Nattanfotos: 135 emojis\n",
      "~ Roberta 🪷: 98 emojis\n",
      "~ Leonardo Trajano: 98 emojis\n",
      "André: 77 emojis\n",
      "~ 🩵Airlania & Faruk🩵: 57 emojis\n",
      "~ Emily: 48 emojis\n"
     ]
    }
   ],
   "source": [
    "import re\n",
    "from collections import Counter\n",
    "\n",
    "file_path = '_chat.txt'\n",
    "# Regex para detectar emojis (faixa Unicode estendida)\n",
    "emoji_pattern = re.compile(r'[\\U00010000-\\U0010ffff]')\n",
    "# Regex para detectar o início de uma mensagem e o conteúdo\n",
    "msg_pattern = re.compile(r'\\[\\d{2}/\\d{2}/\\d{4}, \\d{2}:\\d{2}:\\d{2}\\] (.*?): (.*)')\n",
    "\n",
    "emoji_counts = Counter()\n",
    "user_emoji_counts = Counter()\n",
    "\n",
    "try:\n",
    "    with open(file_path, 'r', encoding='utf-8') as f:\n",
    "        current_user = None\n",
    "        for line in f:\n",
    "            match = msg_pattern.search(line)\n",
    "            if match:\n",
    "                current_user = match.group(1)\n",
    "                content = match.group(2)\n",
    "            else:\n",
    "                content = line\n",
    "            \n",
    "            # Encontra todos os emojis na linha/conteúdo\n",
    "            emojis = emoji_pattern.findall(content)\n",
    "            if emojis:\n",
    "                emoji_counts.update(emojis)\n",
    "                if current_user:\n",
    "                    user_emoji_counts[current_user] += len(emojis)\n",
    "\n",
    "    total_emojis = sum(emoji_counts.values())\n",
    "    print(f\"Total de emojis utilizados: {total_emojis}\")\n",
    "    print(\"-\" * 40)\n",
    "    \n",
    "    print(\"Os 20 emojis mais frequentes:\")\n",
    "    for emoji, count in emoji_counts.most_common(20):\n",
    "        print(f\"{emoji}: {count}\")\n",
    "    \n",
    "    print(\"\\nTop 10 usuários que mais usam emojis:\")\n",
    "    for user, count in user_emoji_counts.most_common(10):\n",
    "        print(f\"{user}: {count} emojis\")\n",
    "\n",
    "except FileNotFoundError:\n",
    "    print(f\"Erro: Arquivo '{file_path}' não encontrado.\")\n",
    "except Exception as e:\n",
    "    print(f\"Erro ao processar: {e}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
